disabled_rules:
    - line_length
    - function_body_length
    - type_body_length
    - file_length
    - generic_type_name
    - force_cast
    - force_try
    - identifier_name
    - type_name
    - todo
    - large_tuple
    - unused_setter_value
    - notification_center_detachment
    - discarded_notification_center_observer
    - cyclomatic_complexity
    - closure_parameter_position
    - statement_position
    - weak_delegate
    - implicit_getter
    - inclusive_language
    - class_delegate_protocol
    - legacy_cggeometry_functions
    - legacy_constructor
    - legacy_hashing
    - multiple_closures_with_trailing_closure
    - nesting
    - function_parameter_count
    - xctfail_message
    - compiler_protocol_init
    - reduce_boolean

included:
    - Wire-iOS/Sources
    - Wire-iOS Tests/
