disabled_rules:
    - no_space_in_method_call
    - return_arrow_whitespace
    - comment_spacing
    - vertical_parameter_alignment
    - closing_brace
    - line_length
    - function_body_length
    - type_body_length
    - file_length
    - generic_type_name
    - force_cast
    - force_try
    - syntactic_sugar
    - identifier_name
    - type_name
    - mark
    - duplicate_imports
    - todo
    - shorthand_operator
    - control_statement
    - unused_closure_parameter
    - redundant_optional_initialization
    - unused_optional_binding
    - void_return
    - large_tuple
    - computed_accessors_order
    - unused_setter_value
    - notification_center_detachment
    - discarded_notification_center_observer
    - cyclomatic_complexity
    - private_over_fileprivate
    - opening_brace
    - empty_parentheses_with_trailing_closure
    - empty_enum_arguments
    - switch_case_alignment
    - unneeded_break_in_switch
    - closure_parameter_position
    - statement_position
    - weak_delegate
    - implicit_getter
    - inclusive_language
    - for_where
    - orphaned_doc_comment
    - class_delegate_protocol
    - legacy_cggeometry_functions
    - legacy_constructor
    - legacy_hashing
    - multiple_closures_with_trailing_closure
    - nesting
    - no_fallthrough_only
    - function_parameter_count
    - redundant_string_enum_value
    - redundant_void_return
    - xctfail_message
    - compiler_protocol_init
    - reduce_boolean
    - redundant_discardable_let

included:
    - Wire-iOS/Sources
    - Wire-iOS Tests/
