env:
  global:
    - secure: DUTI6xnk6emxAGtabSBfFH5QO6jxkRgjCWZp6fnXGrT125ZJ1Gdmf7+O9Gm/qfv9g2zUwjAnptgXUPvPT3xkdB256Ev7eLok9yTwErRd4vubbmxxu7+EqavYg1kQtdb6UStZ5c1Yz/S2mlqOxG5KMQxom80WU9Cfdq096q8hfeJ25hsNdoKBs1EN4Dyb8VxDdTRBHbADE8prqEDtNEprLEYBKzNkH9EbvR/1sPpZ6tsWFKG5mLNifaV/BDfogoFhsgex5EAibpUhXgC4L9zsJMk0Xh8iUOXNkxp7dsOxMeazEtfnUxB26nXUaH2aSopnahmznEtmsKWxLrUheKVKX8rms5fAWTvC8O7p5KYmijzckWGsLK02xRa2lFd71Muw73ZTHL3fLwRJKF7JuU1Aw9bWcVBVjh6rRVaXJloyvJ5rlqvlCWLbUmAJp3QeBJC8MYDenT2G0RIfGEAitNI91IleJrRkX9jmgdzTwa0q+37imIk/H0F4joG4RxXYIx/OU7a95cYvR2pZ9I7jmaRYMlK9jR9huykoP4J2HdsKvkIZhvaIc/wh37B2Pe+tm42vZtcpu3Axym078T5oBs2NDrBYKX0QEpG+eFNA7nshpcPkKvSh2BJN/GFEPgbuSbuzFPYUTmhGOEsM7g1vIsds+rb3zs5/wf48tTiBhPBYh00=
    - secure: vruKxjbwc+5rYxnxWlskv2V8igoW/tYScxH8raJBEGh6ZRhfdUJUGEv5JDrXVvH/bj50oY31U3XkZf/CyfwHnqPbTWWTclTf7EV5SWRI0tU7Lf6hLahSs6EXJv3DWZKjvAq3wxxO/2pPmSynj8nzXh9FaHuw7WixCMNGB0cobb/EdY9ObUsABh/8Wk5v9vCcXShbpUuqzhOQfUj4TERVjX/P77JNFZ+U5zYVcCmRLufLSnxmeOVYnz8b1Ni4ol+0cWowEoCxBjAkGDW1CBKwWWy5l/q+gKRDTLORAQtAiEuXJBaNNGG+s93kkzjfCixALEBPwG3AgyTamkoMkYk6vyD6qhBjF4+aOAVYuiCPa64RyIxxHekTJG6Q6vV0kbZpAHPNuSkK2SYdU8vhtd3+hb9vjyYzpo0Pg2kefpu4i/0bdT82bLWjidCqswI3TzCur3THHdrUzo4K0pxU8UlLPQg4z1KDD4ltQDeLm3+oqumyp0tPRT+LlxY7pzHyWwRsRT0701z5Yuc1pPwX176lg8QDEl93CXoMoeLf6uMgXxeSKf5cogXTi4Ju/WkInW5APitRu1GWhZAQrH0bGGibzg9u9Uu35DQnCq8Sy0HwCwUA64+ISa2gNyGdPC55K7XGjQoW5XJ8JmVpXis3xx7k4Ah0O/P61o92D6qd/JNYV68=
    - secure: HaoBuuI+aLjpCZEx3vA6z5Bh7QxgkIOf2vRQIBID0WqtR6M9OiVys0CoU+etCP6BWGzgYB8NVWoiqFjT6h64UIKdprggnSk8d0tPIwHUiJUspeWpWzvDyqJPZYzv9SnzHqhF1HqILATp/tYK/K8LenflcekPGiE1INdJjpb5wu9TN/MvcUUvLTx2mpmaNHNgcXTf227yeKN95OWUN4KVnkzV1hkcjApu9iLi5Rb0erlz8kyPFLvZhYwUXImyLzBYmSCOn/DN95DtQzwJpfjcWdJk7e/miErHvMnJ+WY4vqZYx51tdt0h9r58o1uD1FHbgiBXYu44a/0UNMMc/jHq2rmqse5V4vDLx7NpChQWZeKWwFMcETburzWngvW92Uc2Fyp89OeCKeQkKQaOS7I1j2TLKUKwB8AhIjDFnLk44y8YLwmo+wgZZLbD6EgG5xDRwm6YbiIdnPICgX3ieySmMN0M2OIX48kyEmPiOgDhCD8lxdD0+FQgH3NVfYM5v6YGkQ6LAlhrz0QV+UWNL7++tSQHHuqh2f5dKMsAIYqhrmnZHgjwYeQVUcy8Wo2Rg7Ew3R2tiMntolmTvk+VsuDUoac0MA4plsdUuoQ4z0aW7Am8lz7F0KfCdCyKRByEAW1/TYSvTmx6H4Yymy2uCo+USoq8q0NOzv5mChfy1xIo8NQ=
    - secure: Zo9w6xTSrzRbxGUpYcqyC66K+5DQj1WCdd5sLc2IbowPgYHPJK2IRoq6lI6CHQRr0WCYquy6R9hz7XLXM4sgdz51FSeXDUTm5M4fZakdauFWGrPsg1OkcjTcItW8xbFdCWBToW1VWZA2EqlxMW/OZujTlJ126wn/JPtb52p45IBpGTksNURjG467hjfuqWLsLldiqb2I8IpPG7u/B8+fnKGGDYSu9ZK65dat+nDVdtCtp5YjmLoPGmd9/JkAdNXwHbk4wrO6dkbKS9BwBYUAOiDUtZL5TSNZFy5CgRMjSaRdUydSTEg1o5p2DQOXR2IDnzrNXmb5+CGaIgNGlzkDAcR3Mj+g7Un73C6hGTji8Aac+KaN0gia3xf1OvI2xVP0PWM3RVI6EoIwBYqcrYCTFhtMVMbSAWGNopJYs/6S/ndtZTBLCe0Ka7zTb4RydEGlMx+VUSzx+4GqK+92zCpNCD9+jhvblkBZtocWbtKjo26jkVadgKYdGfAW+vRZ3SdmFliTQY7wI+lAz/U6lM/xiqS+wGQFMqEYnEtXKed0DkRDcYsFK4I/Kvdny0uMc/VgcR3ChC+pgMZfwMRvnQsNMiZkh4AGeNYl48saQJ8YkAdqZP9Eg/JLeJYDb1ZQkEWGPc6H3Gim8eZtbn82UNR9aPuZ/2W6LjRGKCryQgB4ewE=
    - secure: pL3dEy5WBFJ272FSjnI3XZbwsI1F37aWrnPK7gboSfNGi+Hju+YOM6pCaJte7vmGAVrm8MpLYeAElRbYWbSF7N/mgvUC7L+BcT147RH8KfXQq+eKzgqGl06uA1x1uhEcYiPVdq46ZYWaVhPOIOVxlvT5BCIDfBsOmiy2HuAOto6SD3PR3yQYqp0G+iXflXp3IjAfSP4oJtPy6T8F928//sdrinFq/62YKwmJqhG7pd7Uc8qjUikZ+cfs88anuw0Z5ueLgp3eUAEatPUVprwRIm928Qn5N+7AJRtWb5zts0S/TEn+wHmCihkb3JlTe1qovr749SABUGWyh9ztI0KfM903VBacG6FrEBwv91limyA/giSW1TLh6IGTQml1IDYqZcjsPkJf6/pJHBD4b/quNnCnyG4OlxvW/w9I9HmiNMCb9eekNrNqZoZfgIX/Pqd75cf986C8brnqf20uACTiOsCma1AazM76GRBrxMCTON51BFd4TCI3ecgAPGpnArP0W9z2as73Z2WNt2iFEebqXhghLcdPqLn9ibZMOIX5AOI9yacPVM216T5HLkpqUbMa94mrqGvL0ghXva6Iqj9GgL6++uDWoVJMuH4xHLr9Udx1dFiyCUqBB68wsw14VV+M67/vX1OmxmEAIaRUcxJjVWMDUPF6hSlYy0FNJt9+RUo=

language: ruby
rvm: 2.0.0

notifications:
  email:
    on_success: never
    on_failure: always

branches:
  only:
    - develop
    - master
    - /^release\/.*/

cache:
  bundler: true

install:
  - bundle install
  - curl -O https://raw.githubusercontent.com/wireapp/wire-ios-shared-resources/master/Dangerfile

script:
  - set -o pipefail
  - bundle exec danger
