env:
  global:
  - secure: VN+RjVNjHr8ZTdHn8GFSEjV0eGRt0Uy0DAeu8MT9QYINSF/XdAikbTyDp+O+N8qsif3hbifUqpftkdo0P3gvGOzZ4AVQfTDoRC2IChMb+pGLIdZFTjLqQOWoC0VLYOvTlpA70X0E92KVe1Zlpbo4GXLAbdG8gNfEOoL1kCbMUfdSFZrZ31njIJjb6W07UALiyHnV1o6KpOS6pEXQZOiZ/y31maAwBJv8NI3ZPx1td2wXPDv/yjX8+gKNH0NZ5RPcToc46nLQDmRPKIrMmPeco+V047DHuMeDRN6RM790lBUhER/dv/vcZdBYlwN2+7q1bv7q5sBDWCwUsmxi8xNmekwDhz7iXvApvQfTxdMrZkt84i2U90Aop9URoki4nRZ0o+xRGEH1NTGQDMD6xxxX6GAqAJBL7qSb5QnkBMgPxkA8OcfvxuwKOZE+x0CE/jhYVEi67GTZrBtXnANBE+gLYdHTt1jr8lilYmbbs0KwBP9BhARpA4n1FKkm6QSsAPphceyjaewMkH5nkqNVRWQr65sjFHwn62b/ARFlZXPS0Au9qiUO6b5bE4Bz+tAOwkuh7iiSqFZgcAZoaSZoXz6dQ413V8wo1ePQ++F7kHv8KcI1O2AxJrhkgNEv+EfOhS7qQOd+r9WxBbPCxY67C1zoBmz+COY5jqRcINf3jV5LnLc=
  - secure: s1lfIDuj8Jzu6JSfrW2/pu7VKq4i9Qz7rWfKVoqBdzmeyRS2q1+NsG3I3bIhc+Aj1eQXUeHh/GFvr2ij4gahpIO2XhcArPliCK23hovq6mnkYaS4JS9R2pnxKDPHvxktNcHZkCfdlL2rlLyPWAkDgidDCZTa7EoV4tg4qGvZP7YHKH/Tq0NNziiOJlHD+kddNS5fljjJtV1idvBL3Pmls9gPGUpaQnJuNonPW6OKQvdMHaczQ5P76c7ccigGGUEgmUsn/0x9bb7cwsEGXIxXgrPq0QyNTWDKkJNyk7HywWUpDmaJ30CVHnerdeTZRMhBJT/y/Vn0zV+VvbKh7fWMeUuuTZkjpOJ+CZWDewIWSOuiZSrV8OU4Dyuf2jtHv6Dr1sJWC8PqXO9CBS/Lh4ynkgoIAE8udrfLVIiN7KlGK+yvDOcMn7S7vudZ7aXONRVappDDdFzLnThiNbLx7G0Mqxtv1bA8eMysRM46uj+kcEvOHcwRxmvUbmezoJEPTEwbC8yABMZ37gCnnWfxe1qI6/i2sooI+4Ojd/MtLyKR0D5MD6/WbJgSrChmpsSuJY5LDeeh85Pndb6F3BT3R2/KeJ4HT+uWK7STdBFRs6c2yQgElKJj0PMGwZ1CDHe/AZswT5atH7VrEjwoX5Hy4SiVjKkFLnzmNW3f2ZJuXnf3+tE=

language: ruby
rvm: 2.0.0

notifications:
  email:
    on_success: never
    on_failure: always

branches:
  only:
    - develop
    - master
    - /^release\/.*/

cache:
  bundler: true

install:
  - bundle install
  - curl -O https://raw.githubusercontent.com/wireapp/wire-ios-shared-resources/master/Dangerfile

script:
  - set -o pipefail
  - bundle exec danger
