language: objective-c
osx_image: xcode7.3

cache:
  - bundler
  - cocoapods

script:
  - open -b com.apple.iphonesimulator
  - set pipefail
  - ./setup.sh
  - xcodebuild build test -workspace Wire-iOS.xcworkspace -scheme Wire-iOS -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.3' | xcpretty
