pool:
   vmImage: 'macOS 10.13'

trigger:
  - develop

variables:
  DEPENDENCIES_BASE_URL: "https://raw.githubusercontent.com/wireapp/wire-ios-shared-resources/master"
  GITHUB_ACCESS_TOKEN: $(GITHUB_ACCESS_TOKEN)
steps:
- script: |
    sudo xcode-select -switch /Applications/Xcode_10.app
    bundle install --path ~/.gem
    bundle exec fastlane prepare     
  displayName: "Setup environment"
- script: |
    bundle exec fastlane build
  displayName: "Build"
- script: |
    bundle exec fastlane test
  displayName: "Test"
- task: PublishTestResults@2
  inputs:
    testResultsFiles: 'test/*.xml'
- script: |
    bundle exec fastlane test
  displayName: "Post Test"
