pool:
   vmImage: 'macOS 10.13'

trigger:
  - develop

variables:
  scheme: "Wire-iOS"
  sdk: "iphonesimulator"
  configuration: "Debug"
  project: "Wire-iOS.xcodeproj"
  
steps:
- script: |
    sudo xcode-select -switch /Applications/Xcode_10.app
    ./setup.sh 
    mkdir SnapshotResults
  env:
    GITHUB_ACCESS_TOKEN: $(GITHUB_ACCESS_TOKEN)   
  displayName: "Setup environment"
- task: Xcode@5
  inputs:
    actions: "build-for-testing"
    scheme: "$(scheme)"
    sdk: "$(sdk)"
    configuration: '$(configuration)'
    xcodeVersion: 'default'
    packageApp: false
    xcWorkspacePath: "$(project)"
    destinationSimulators: 'iPhone 7'
    destinationTypeOption: 'simulators'
    destinationPlatformOption: 'iOS'
    useXcpretty: true
  displayName: "Build"
- task: Xcode@5
  inputs:
    actions: "test-without-building"
    scheme: "$(scheme)"
    sdk: "$(sdk)"
    configuration: '$(configuration)'
    xcodeVersion: 'default'
    packageApp: false
    xcWorkspacePath: "$(project)"
    destinationSimulators: 'iPhone 7'
    destinationTypeOption: 'simulators'
    destinationPlatformOption: 'iOS'
    useXcpretty: true
    publishJUnitResults: true
  displayName: "Test"
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: "SnapshotResults"
    artifactName: "Snapshot failures"
    condition: failed()
- script: |
    bundle exec fastlane post_test
  env:  
    CODECOV_TOKEN: $(CODECOV_TOKEN)
    DEPENDENCIES_BASE_URL: "https://raw.githubusercontent.com/wireapp/wire-ios-shared-resources/master"
    GITHUB_ACCESS_TOKEN: $(GITHUB_ACCESS_TOKEN)   
  displayName: "Post Test"
