# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

source 'https://rubygems.org'

gem 'fastlane'
gem 'danger'
gem 'danger-xcode_summary'
gem 'xcpretty-json-formatter'
gem 'fastlane-plugin-trainer'
gem 'fastlane-plugin-xcpretty_report'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
