opt_out_usage
default_platform(:ios)

platform :ios do

    desc "Fetch dependencies"
    lane :prepare do
        sh "cd .. && ./setup.sh"
    end


    desc "Build for testing"
    lane :build do
        scan(
            scheme: "Wire-iOS",
            build_for_testing: true,
            clean: true,
            devices: ["iPhone 7"],
            code_coverage: true,
            output_directory: "build",
            output_types: "junit",
            buildlog_path: "build",
            derived_data_path: "DerivedData",
            formatter: "xcpretty-json-formatter"
        )
    end

    desc "Test without building"
    lane :test do
        scan(
            scheme: "Wire-iOS",
            test_without_building: true,
            devices: ["iPhone 7"],
            code_coverage: true,
            buildlog_path: "test",
            derived_data_path: "DerivedData",
            output_types: "",
            fail_build: false
        )
        trainer(output_directory: "test")
    end

end
