name: Crowdin Action

on:
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Crowdin action
        uses: wireapp/github-action@1.1.0
        with:
          # For more info: https://github.com/crowdin/github-action/blob/master/action.yml
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}          
          token: ${{ secrets.CROWDIN_API_TOKEN }}
          config: crowdin.yml
          
          upload_sources: true
          download_translations: true
          upload_translations: false

          create_pull_request: true
          localization_branch_name: chore/update-localization
          commit_message: "[Chore] Update localization"
          pull_request_title: "[Chore] Update localization"
          pull_request_body: "This PR pulls in the latest localization translations from Crowdin."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
