name: Xcode 12 iOS 14 Simulator Test

on: 
  workflow_dispatch:
  pull_request:
    branches:
      - develop
jobs:
  Run_Tests_Xcode_12_0_iOS_14_4:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.4.app && /usr/bin/xcodebuild -version
      
    - name: Carthage
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bash setup.sh

    - name: Run tests
      run: xcodebuild test -scheme Wire-iOS -project Wire-iOS.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 8,OS=14.4' | xcpretty && exit ${PIPESTATUS[0]}

    - name: Archive SnapshotResults artifacts
      uses: actions/upload-artifact@v2
      with:
        name: snapshotResults
        path: SnapshotResults
